import { notFound } from 'next/navigation';
import Link from 'next/link';

const posts = {
  'cyber-security-roadmap-2026': { category:'CYBER SECURITY', title:'Cyber Security Career Roadmap 2026', intro:'A practical path from security foundations to SOC and offensive security roles.', sections:[['Start with foundations','Networking, operating systems, authentication, common attack patterns and security principles give you the vocabulary to investigate problems confidently.'],['Practice the workflow','Use labs to inspect logs, investigate alerts, understand vulnerabilities and document findings. The goal is repeatable process, not memorized commands.'],['Build evidence','A small set of well-documented projects is more useful than a long list of unfinished tutorials. Show what you investigated, how you reasoned and what you changed.']] },
  'ai-engineer-roadmap': { category:'AI ENGINEERING', title:'What an AI Engineer Actually Builds', intro:'AI engineering sits at the intersection of software engineering, machine learning and modern LLM systems.', sections:[['Python and data','Strong Python, APIs, data handling and software fundamentals are the base layer for AI applications.'],['Models and systems','Learn model behavior, prompting, embeddings, retrieval, evaluation and how AI components fit into production systems.'],['Real applications','Build useful applications such as RAG assistants, workflow agents and AI-powered internal tools — with reliability and evaluation in mind.']] },
  'data-analyst-vs-data-scientist': { category:'DATA SCIENCE', title:'Data Analyst vs Data Scientist', intro:'Both roles work with data, but the day-to-day problems, technical depth and expected outputs differ.', sections:[['Data Analyst','Analysts typically spend more time on SQL, reporting, dashboards, business questions and communicating what happened.'],['Data Scientist','Data scientists work deeper with statistics, experimentation, predictive modeling and machine learning.'],['Choosing your start','Pick the path that matches the work you want to do. Strong SQL, Python and analytical thinking are useful foundations for both.']] },
} as const;

export function generateStaticParams(){return Object.keys(posts).map(slug=>({slug}));}
export default async function InsightPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=posts[slug as keyof typeof posts];if(!post)notFound();return <main><section className="simple-hero"><div className="section"><Link className="back-link" href="/insights">← All insights</Link><div className="eyebrow">{post.category}</div><h1>{post.title}</h1><p>{post.intro}</p></div></section><article className="article section">{post.sections.map(([heading,text])=><section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}</article><section className="cta"><div className="cta-inner"><div><div className="eyebrow">READY TO BUILD?</div><h2>Turn reading into a learning plan.</h2><p>Book a free Institute 9 session and choose the right track for your goals.</p></div><Link className="session-button large" href="/#free-session"><span>Book a</span><strong>Free Session</strong><em>→</em></Link></div></section></main>}
