import Link from 'next/link';

export const metadata = { title: 'About Institute 9 | Career-Focused Technology Education' };

export default function AboutPage() { return <main>
  <section className="simple-hero"><div className="section"><div className="eyebrow">ABOUT INSTITUTE 9</div><h1>Built for learners who want to do, not just watch.</h1><p>Institute 9 is a career-focused technology education brand built around practical learning in Cyber Security, AI Engineering and Data Science.</p></div></section>
  <section className="section about-grid"><div><div className="eyebrow">OUR APPROACH</div><h2>Education should create capability.</h2><p className="lead">We design learning paths around the actual work behind modern technology roles. That means fundamentals, tools, labs, projects, feedback and career context — not a long list of videos.</p><p className="lead">Our goal is simple: help learners build enough understanding and evidence of skill to take their next career step with confidence.</p></div><div className="about-points"><article><strong>01</strong><h3>Industry relevance</h3><p>Curriculum is mapped to modern tools, workflows and role expectations.</p></article><article><strong>02</strong><h3>Hands-on by design</h3><p>Labs and projects are part of the learning path, not an afterthought.</p></article><article><strong>03</strong><h3>Career context</h3><p>Learning connects to portfolios, interviews and real-world problem solving.</p></article></div></section>
  <section className="dark-section"><div className="section"><div className="eyebrow light">OUR THREE TRACKS</div><h2>One institute. Three high-demand paths.</h2><div className="method-grid"><div><strong>01</strong><h3>Cyber Security</h3><p>Defend systems, investigate threats and understand offensive security.</p></div><div><strong>02</strong><h3>AI Engineering</h3><p>Build AI-powered systems with Python, ML, LLMs and modern AI tooling.</p></div><div><strong>03</strong><h3>Data Science</h3><p>Turn data into analysis, models, dashboards and decisions.</p></div><div><strong>→</strong><h3>Start with a free session</h3><p><Link href="/#free-session">Talk to Institute 9 admissions.</Link></p></div></div></div></section>
</main>; }
